config/routes.rb
Rails.application.routes.draw do
  get '/friends', to: 'friends#index'
  get '/notifications', to: 'notifications#index'
  get '/search', to: 'search#index'
  resources :posts
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, only: [:index, :show]
  get 'invitations/update'
  get 'invitations/create'
  get 'invitations/destroy'

  get 'likes/create'
  get 'likes/destroy'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [ :destroy ]
  before_action :require_appropriate_user, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    @comment.save

    redirect_to post_path(@comment.post)
  end

  def destroy
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end

    def require_appropriate_user
      if current_user.id != @comment.user_id
        flash[:alert] = "You must be creator of that comment to handle that operation"
        redirect_to @post
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.reverse_each do |comment| %>
  <div class='comment'>
    <div class='profile-img-small'>
      <%= image_tag 'avatar.png', class:'profile-img' %>
    </div>
    <div class='comment-container'>
      <div>
        <div>
          <%= link_to comment.user.first_name, user_path(comment.user), class:'comment-user' %>
          <%= link_to comment.user.last_name, user_path(comment.user), class:'comment-user' %>
          <span class='comment-date'><%= time_ago_in_words(comment.created_at) %></span>
        </div>
        <div><%= comment.body %></div>
      </div>
      <div data-controller="dropdown" class="dropdown">
        <button type="button" data-action="dropdown#toggle click@window->dropdown#hide" class='dropdown__button'>&#8942;</button>
        <div
          data-dropdown-target="menu"
          class="dropdown__menu hidden"
        >
          <% if current_user.id == comment.user_id %>
            <div data-action="dropdown#toggle"><%= link_to 'Delete', post_comment_path(comment.post, comment), data: { turbo_method: :delete }, class:'dropdown__menu-link' %></div>
          <% end %>
          <a data-action="dropdown#toggle" class='dropdown__menu-link'>Report</a>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [ @post, @comment ] do |form| %>

  <div class='post-form'>
    <%= form.text_field :body, class:'post-form__input post-form__input-full' %>
    <div>
      <%= form.submit 'Submit', class:'btn btn--secondary btn--fitted' %>
    </div>
  </div>

<% end %>