config/routes.rb
Rails.application.routes.draw do
  get '/friends', to: 'friends#index'
  get '/notifications', to: 'notifications#index'
  get '/search', to: 'search#index'
  resources :posts
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, only: [:index, :show]
  get 'invitations/update'
  get 'invitations/create'
  get 'invitations/destroy'

  get 'likes/create'
  get 'likes/destroy'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :invitations
  has_many :pending_invitations, -> { where confirmed: false }, class_name: 'Invitation', foreign_key: 'friend_id'

  def friends
    friends_i_sent_invitations = Invitation.where(user_id: id, confirmed: true).pluck(:friend_id)
    friends_i_got_invitations = Invitation.where(friend_id: id, confirmed: true).pluck(:user_id)
    ids = friends_i_sent_invitations + friends_i_got_invitations
    User.where(id: ids)
  end

  def friend_with?(user)
    Invitation.confirmed_record?(id, user.id)
  end

  def send_invitation(user)
    invitations.create(friend_id: user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(:user_id => current_user.friends).or(Post.where(:user_id => current_user))
  end

end

app/views/users/index.html.erb
<div class='users_list'>
  <% @users.each do |user| %>
    <div class='user'>
      <div class='profile-img-small'>
        <%= image_tag 'avatar.png', class:'profile-img' %>
      </div>
      <div class='user__name'>
        <%= link_to user.first_name, user_path(user), style:'color: var(--color-text-header);' %>
        <%= link_to user.last_name, user_path(user), style:'color: var(--color-text-header);' %>
      </div>

      <% if signed_in? && !Invitation.reacted?(current_user.id, user.id) && current_user != user %>

        <%= link_to 'Add Friend', invitations_create_path(ids: {id1: current_user.id, id2: user.id}), class:'btn btn--secondary' %>

      <% elsif signed_in? && Invitation.reacted?(current_user.id, user.id) && !Invitation.confirmed_record?(current_user.id, user.id) && current_user != user %>

        <div class='btn btn--muted'>Pending |
        <%= link_to 'X', invitations_destroy_path(invitation_id: Invitation.find_invitation(current_user.id, user.id)) %>
        </div>

      <% elsif signed_in? && Invitation.confirmed_record?(current_user.id, user.id) && current_user != user  %>

        <div class='btn btn--muted'>Friend</div>

      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='profile'>
  <div class='profile-data'>
    <div class='profile-img-normal'>
      <%= image_tag 'avatar.png', class:'profile-img' %>
    </div>
    <div class='profile-name' style='display:flex; flex-direction:column; justify-content:center;'>
      <div>
        <%= @user.first_name %>
        <%= @user.last_name %>
      </div>
      <% if signed_in? && !Invitation.reacted?(current_user.id, @user.id) && current_user != @user %>

        <%= link_to 'Add friend', invitations_create_path(ids: {id1: current_user.id, id2: @user.id}), class:'btn btn--secondary' %>

      <% elsif signed_in? && Invitation.confirmed_record?(current_user.id, @user.id) && current_user != @user %>

        <div>
          <%= link_to 'Unfriend', invitations_destroy_path(invitation_id: Invitation.find_invitation(@user.id, current_user.id)), class:'btn btn--primary' %>
        </div>

      <% elsif signed_in? && Invitation.reacted?(current_user.id, @user.id) && !Invitation.confirmed_record?(current_user.id, @user.id) && current_user != @user %>
        <% if Invitation.find(Invitation.find_invitation(current_user.id, @user.id)).user_id == current_user.id %>

          <div class='btn btn--muted'>Pending |
            <%= link_to 'X', invitations_destroy_path(invitation_id: Invitation.find_invitation(current_user.id, @user.id)) %>
          </div>

        <% elsif Invitation.find(Invitation.find_invitation(current_user.id, @user.id)).friend_id == current_user.id %>

          <div style='display: flex;'>
            <%= link_to ("<div>&#10003;</div>").html_safe,
            invitations_update_path(invitation_id: Invitation.find_invitation(current_user.id, @user.id)), class:'btn btn--secondary' %>
            <%= link_to 'X',
            invitations_destroy_path(invitation_id: Invitation.find_invitation(current_user.id, @user.id)), class: 'btn btn--primary' %>
          </div>

        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class='profile-friends'>
  <div class='profile-friends-container'>
    <%= link_to friends_path(id: @user.id) do %>
      <div class='profile-friends-heading'>
        Friends(<%= @user.friends.count %>)
      </div>
    <% end %>
  </div>
  <div class='users_list__OP'>
    <% @user.friends.last(6).reverse_each do |friend| %>
      <div class='user__OP'>
        <div class="user__data__OP">
          <div class='profile-img-medium'>
            <%= image_tag 'avatar.png', class:'profile-img' %>
          </div>
          <div class='user__name__OP'>
            <%= link_to friend.first_name, user_path(friend), style:'color: var(--color-text-header);' %>
            <%= link_to friend.last_name, user_path(friend), style:'color: var(--color-text-header);' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div id="posts">
  <% @posts.reverse_each do |post| %>
    <%= render post %>
  <% end %>
</div>