config/routes.rb
Rails.application.routes.draw do
  get '/friends', to: 'friends#index'
  get '/notifications', to: 'notifications#index'
  get '/search', to: 'search#index'
  resources :posts
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, only: [:index, :show]
  get 'invitations/update'
  get 'invitations/create'
  get 'invitations/destroy'

  get 'likes/create'
  get 'likes/destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_appropriate_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    #@posts = Post.all
    @posts = Post.where(:user_id => current_user.friends).or(Post.where(:user_id => current_user))
    @post_new = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :body)
    end

    def require_appropriate_user
      if @post.user != current_user
        flash[:alert] = "You must be creator of that article to handle that operation."
        redirect_to @post
     end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div class='error-message'>
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='post'>
    <div class='post__user'>
      <div class='profile-img profile-img-small'></div>
      <div class='post__user-name'>
        <%= link_to post.user.first_name, user_path(post.user), style:'color: var(--color-text-header);' %>
        <%= link_to post.user.last_name, user_path(post.user), style:'color: var(--color-text-header);' %>
        <div class='post__date'>
          <%= time_ago_in_words(post.created_at) %>
        </div>
      </div>
    </div>

    <div class='post__body'>
      <%= form.text_field :body, :required => 'required', class:'post-form__input' %>
    </div>

    <div style='width: 100%; display: flex; justify-content: flex-end; padding: 1rem;'>
      <%= form.submit 'Submit', class:'btn btn--secondary btn--fitted' %>
    </div>
  </div>

<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class='post-form'>
    <div class='profile-img-small'>
      <%= image_tag 'avatar.png', class:'profile-img' %>
    </div>

    <%= form.text_field :body, :required => 'required', class:'post-form__input', placeholder:'What is on your mind?' %>

    <div>
      <%= form.submit 'Submit', class:'btn btn--secondary btn--fitted' %>
    </div>
  </div>

  <% if post.errors.any? %>
    <div class='error-message'>
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id(post) %>" class='post'>
  <div class='post__header'>
    <div class='post__user'>
      <div class='profile-img-small'>
        <%= image_tag 'avatar.png', class:'profile-img' %>
      </div>
      <div class='post__user-name'>
        <%= link_to post.user.first_name, user_path(post.user), style:'color: var(--color-text-header);' %>
        <%= link_to post.user.last_name, user_path(post.user), style:'color: var(--color-text-header);' %>
        <div class='post__date'>
          <%= time_ago_in_words(post.created_at) %>
        </div>
      </div>
    </div>
    <div data-controller="dropdown" class="dropdown">
      <button type="button" data-action="dropdown#toggle click@window->dropdown#hide" class='dropdown__button'>&#8942;</button>

      <div
        data-dropdown-target="menu"
        class="dropdown__menu hidden"
      >
        <% if post.user == current_user %>
          <div data-action="dropdown#toggle"><%= link_to "Edit", edit_post_path(post), class:'dropdown__menu-link' %></div>
          <div data-action="dropdown#toggle"><%= link_to "Delete", post, data: { turbo_method: :delete }, class:'dropdown__menu-link' %></div>
        <% end %>
        <a data-action="dropdown#toggle" class='dropdown__menu-link'>Report</a>
      </div>
    </div>
  </div>


  <div class='post__body' data-controller='read-more' data-read-more-toggle-class='post__body-text'>
    <div class='post__body-text' data-read-more-target='text'><%= post.body %></div>
    <% if post.body.length > 430 %>
      <div class='help-link' data-action="click->read-more#update" data-read-more-target='button'>Read more...</div>
    <% end %>
    <div style='display: flex; gap: .5rem;'>
      <% if post.likes.count > 0 %>
        <div class='post__body-likes'>
        <%= post.likes.count %>
        <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
        </div>
      <% end %>
      <% if post.comments.count > 0 %>
        <div class='post__body-likes'>
          <%= post.comments.count %>
          <%= (post.comments.count) == 1 ? 'Comment' : 'Comments'%>
        </div>
      <% end %>
    </div>
  </div>

  <div class='post__footer'>
    <div class="post__action">
      <% if signed_in? && !Like.liked?(current_user.id, post.id) %>
        <%= link_to image_tag('like-black.png', width: 25, height: 25), likes_create_path(ids: {id1: current_user.id, id2: post.id}, anchor: dom_id(post)) %>
      <% elsif signed_in? && Like.liked?(current_user.id, post.id) %>
        <%= link_to image_tag('like-green.png', width: 25, height: 25), likes_destroy_path(like_id: Like.find_like_id(current_user.id, post.id), anchor: dom_id(post)) %>
      <% end %>
    </div>
    <div class='post__line'></div>
    <div class="post__action">
      <%= link_to image_tag('comment.png', width: 25, height: 25), post %>
    </div>
  </div>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "edit_form", post: @post %>

app/views/posts/index.html.erb
<%= render "form", post: @post_new %>

<div id="posts">
  <% @posts.reverse_each do |post| %>
    <%= render post %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= link_to raw("&#8592; Back to posts"), root_path, class:'help-link' %>
<%= render @post %>
<%= render 'comments/form' %>
<%= render 'comments/comments' %>