config/routes.rb
Rails.application.routes.draw do
  get '/friends', to: 'friends#index'
  get '/notifications', to: 'notifications#index'
  get '/search', to: 'search#index'
  resources :posts
  resources :posts do
    resources :comments
  end
  root 'posts#index'

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :users, only: [:index, :show]
  get 'invitations/update'
  get 'invitations/create'
  get 'invitations/destroy'

  get 'likes/create'
  get 'likes/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user

  def self.reacted?(id1, id2)
    case1 = !Invitation.where(user_id: id1, friend_id: id2).empty?
    case2 = !Invitation.where(user_id: id2, friend_id: id1).empty?
    case1 || case2
  end

  def self.confirmed_record?(id1, id2)
    case1 = !Invitation.where(user_id: id1, friend_id: id2, confirmed: true).empty?
    case2 = !Invitation.where(user_id: id2, friend_id: id1, confirmed: true).empty?
    case1 || case2
  end

  def self.find_invitation(id1, id2)
    if Invitation.where(user_id: id1, friend_id: id2).empty?
      Invitation.where(user_id: id2, friend_id: id1)[0].id
    else
      Invitation.where(user_id: id1, friend_id: id2)[0].id
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user

  def self.liked?(id1, id2)
    case1 = !Like.where(user_id: id1, post_id: id2).empty?
    case2 = !Like.where(user_id: id2, post_id: id1).empty?
    case1 || case2
  end

  def self.find_like_id(id1, id2)
    if Like.where(user_id: id1, post_id: id2).empty?
      Like.where(user_id: id2, post_id: id1)[0].id
    else
      Like.where(user_id: id1, post_id: id2)[0].id
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :invitations
  has_many :pending_invitations, -> { where confirmed: false }, class_name: 'Invitation', foreign_key: 'friend_id'

  def friends
    friends_i_sent_invitations = Invitation.where(user_id: id, confirmed: true).pluck(:friend_id)
    friends_i_got_invitations = Invitation.where(friend_id: id, confirmed: true).pluck(:user_id)
    ids = friends_i_sent_invitations + friends_i_got_invitations
    User.where(id: ids)
  end

  def friend_with?(user)
    Invitation.confirmed_record?(id, user.id)
  end

  def send_invitation(user)
    invitations.create(friend_id: user.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [ :destroy ]
  before_action :require_appropriate_user, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.user = current_user

    @comment.save

    redirect_to post_path(@comment.post)
  end

  def destroy
    @comment.destroy

    redirect_to post_path(@post)
  end

  private

    def set_comment
      @post = Post.find(params[:post_id])
      @comment = @post.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end

    def require_appropriate_user
      if current_user.id != @comment.user_id
        flash[:alert] = "You must be creator of that comment to handle that operation"
        redirect_to @post
      end
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @user = User.find(params[:id])
    @friends = @user.friends
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include ActionView::RecordIdentifier

  def create
    id1 = params[:ids][:id1]
    id2 = params[:ids][:id2]
    @post = Post.find(id2)
    @like = Like.new(user_id: id1, post_id: id2)
    @like.save
    redirect_to posts_path(@post, anchor: dom_id(@post))
  end

  def destroy
    like = Like.find(params[:like_id])
    @post = Post.find(like.post_id)
    like.destroy
    redirect_to posts_path(@post, anchor: dom_id(@post))
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_appropriate_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    #@posts = Post.all
    @posts = Post.where(:user_id => current_user.friends).or(Post.where(:user_id => current_user))
    @post_new = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :body)
    end

    def require_appropriate_user
      if @post.user != current_user
        flash[:alert] = "You must be creator of that article to handle that operation."
        redirect_to @post
     end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    key = "%#{params[:search]}%"
    @users = ''

    if params[:search] != ''
      @users = User.where("first_name LIKE ? OR last_name LIKE ?", key, key)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(:user_id => current_user.friends).or(Post.where(:user_id => current_user))
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_navbar.html.erb
<% if current_user %>
  <header class='navbar'>
    <h1>Post<span>It</span></h1>
    <input type='checkbox' role='button' id='hamburger' class='navbar__checkbox visually-hidden'></input>
    <label class='navbar__toggle' for='hamburger'>
      <span class='navbar__toggle-icon' aria-hidden='true'>
      </span>
      <span class='visually-hidden'>Menu</span>
    </label>
    <div class='navbar__links'>
      <%= link_to image_tag('home.png'), root_path %>
      <%#= link_to 'Users', users_path, class:'navbar__link' %>
      <%= link_to image_tag('search.png'), search_path %>
      <div>
        <%= link_to image_tag('bell.png'), notifications_path %>
        <% if current_user.pending_invitations.any? %>
          <span class='notifications-count'><%= current_user.pending_invitations.count %></span>
        <% end %>
      </div>
      <%= link_to image_tag('user.png'), user_path(current_user) %>
      <%= link_to image_tag('settings.png'), edit_user_registration_path %>
      <a class='navbar__link'>
        <%= link_to image_tag('logout.png'), destroy_user_session_path, method: :delete  %>
      </a>
    </div>
  </header>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostIt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <% if current_user %>
        <% flash.each do |type, msg| %>
          <% if alert %>
            <div class='error-message' data-controller="removals">
              <%= msg %>
              <div data-action="click->removals#remove" class="error-message__close">&times;</div>
            </div>
          <% elsif notice %>
            <div class='error-message error-message-green' data-controller="removals">
              <%= msg %>
              <div data-action="click->removals#remove" class="error-message__close">&times;</div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>